// Centralized route paths for the app
export const ROUTES = {
  root: '/',
  dashboard: '/dashboard',
  actionCreate: '/actions/new',
  track: '/track',
  rewards: '/rewards',
  about: '/about',
  contact: '/contact',
  home: '/home',
  faq: '/faq',
  actionDetailsPattern: '/actions/:id',
  actionDetails: (actionId: number | string) => `/actions/${actionId}`,
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  passwordResetRequest: '/forgot-password',
  passwordResetConfirm: '/reset-password',
  profile: '/profile',
  verifyEmailChange: '/verify-email-change',
  partners: '/partners',
};
